services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123

  mariadb:
    image: mariadb:lts
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 123